### ISSUE TITLE
New LOGO

### ISSUE THREAD

**Issue by gargvarun250** [shantanu109/WolfJobs#6]
Update the previous logo for wolfjobs.

**Comment by Sahil-Nande** [comment]
Creating a new logo. Choosing Red and White as the color scheme.

**Comment by leanneserrao** [comment]
Red and white sounds good. Do you have any particular logo in mind?

**Comment by Sahil-Nande** [comment]
How's this?
![WolfJobs Logo](https://user-images.githubusercontent.com/89487138/140201307-58eca158-3045-48d2-9053-f623f2951a44.png)

**Comment by leanneserrao** [comment]
It's perfect!! Good job
